import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Tracker from "./track";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Penyewaan Iphone | Pixelnesia",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo_pixel.png", //logoweb
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Tracker />
        {children}
      </body>
    </html>
  );
}
